MIN_PASSWORD_LENGTH = 8
MAX_PASSWORD_LENGTH = 64

LOWER_ASCII_CODE = 31
UPPER_ASCII_CODE = 129

INVALID_CHARACTERS = Error: Invalid Characters
TOO_SHORT = Error: Too Short
TOO_LONG = Error: Too Long
TOO_COMMON = Error: Too Common
